language: node_js
node_js:
  - '8'
  - '10'

before_script:
  - yarn install
script:
  - yarn lint
  - yarn test
after_success:
  - yarn coverage
  - yarn coveralls

cache:
  directories:
    - node_modules

#deploy:
#  provider: npm
#  email: tannerntannern@gmail.com
#  api_key:
#    secure:
#  on:
#    tags: true
#    branch: master
#    node: '10'
#    repo: tannerntannern/adapter
