language: node_js
node_js:
  - '8'
  - '10'

before_script:
  - yarn install
script:
  - yarn build-clean
  - yarn lint
  - yarn test
after_success:
  - yarn coverage
  - yarn coveralls

cache:
  directories:
    - node_modules

deploy:
  skip_cleanup: true
  provider: npm
  email: tannerntannern@gmail.com
  api_key:
    secure: "X2PaJSjekc+M2Z+UVKndZUf+t0WJP5GVvYmwExyDR0qf1wr/X63yOgDNVM0KYV9VCgRf69TP5HTTRRLfHBs3IfkbwMqhmz9KJy8T6G+OdS8pXoEfYuFZZ6mCs6ZjUFoSvG5r/b0sToYjzICW0FSNC/4DNbxRtPDRljx6wlp2ZHm7uLf/gEYapWOdQ3BX0nldN9d5nBGrmnMM8iDtgHDnSqYd6DxIm3htjifco5m/h+okGp+hv5YAWEs5M6XPt69QOl+O4+cC/1yhuWoo4ab9DngiAyDuPfa/3wjfKBKXCjrxp+2zHf7IYPoD580TDarDi/Sl/u/R0ge8CXE/w2uw7e3ECzNH9KAKunUZde5+6RgW10nGnOdNAwZ36OQgpfw+i4BeoT3MWYg+A0ONcfFMYwE7wWmHH5v6ufci432w0GXM1V483aEszdwfSTYzhq4wXmwQZcB9Z5yQ8p6oYuUuoy9z+vUSLsgmu5ITehP1uOE5jgmKnIV2bCrHQjgVErYWrqCpfjCvaH6I+XPBTBKgDVaNV9GQS2aUaQc351C4k1iVIEI0xUvWZQZs0DRyA3A9hqUCfElB55LAdgSgrgFWNs6eTM10xx02dXy2hBSyfWZa5XS804E8CPq1gffuYeq6AO36vYlY2eFn88u5gtLUoyLHK2deaH3enRGT605LjcQ="
  on:
    tags: true
    branch: master
    node: '10'
    repo: tannerntannern/adapter
